import { chromium } from 'playwright';
import { preview } from 'vite';
const D = '/tmp/claude-0/-home-claude/0b009c91-1550-55da-92c7-a365df746021/scratchpad';
const servidor = await preview({ preview: { port: 4399, strictPort: false }, logLevel: 'silent' });
const nav = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--autoplay-policy=no-user-gesture-required'] });
const ctx = await nav.newContext({ viewport: { width: 1440, height: 900 } });
const p = await ctx.newPage();
const errores = [];
p.on('pageerror', (e) => errores.push('pageerror ' + e.message));
p.on('console', (m) => (m.type() === 'error' || m.type() === 'warning') && errores.push(m.type() + ' ' + m.text()));
await p.goto(servidor.resolvedUrls.local[0] + '?limpio');
await p.waitForFunction(() => window.chispa);
const [elegir] = await Promise.all([p.waitForEvent('filechooser'), p.click('button[title^="Abrir un proyecto"]')]);
await elegir.setFiles('proyectos/arena-de-habilidades/arena-de-habilidades.chispa.json');
await p.waitForTimeout(600);
const dlg = await p.$('.dialogo button:has-text("Abrir")');
if (dlg) await dlg.click();
await p.keyboard.press('F5');
await p.waitForTimeout(1000);
const orden = async (texto) => {
  await p.fill('.orden-consola', texto);
  await p.press('.orden-consola', 'Enter');
  await p.waitForTimeout(150);
};
await orden('escena.cambiar("Arena")');
await p.waitForTimeout(1200);
const oleada = process.argv[2] ?? '6';
await orden(`buscar("Director").saltarA(${oleada})`);
await orden('buscar("Jugador").vidaMax = 3000');
await orden('buscar("Jugador").curar(3000)');
await orden('buscar("Jugador").carga = 100');
await p.screenshot({ path: `${D}/b0-consola.png` });
await p.click('button[title^="Ver el juego en grande"]');
await p.locator('canvas.lienzo-juego').click({ position: { x: 700, y: 400 } });
for (let i = 0; i < 60; i++) {
  const k = ['w', 'd', 's', 'a'][Math.floor(i / 6) % 4];
  await p.keyboard.down(k);
  await p.keyboard.press(['2', '2', '3', '2', '1', '2', '4', '5'][i % 8]);
  await p.keyboard.press(' ');
  await p.waitForTimeout(120);
  await p.keyboard.up(k);
  if (await p.$('.no-existe')) break;
  if (i % 15 === 7) await p.screenshot({ path: `${D}/b${1 + Math.floor(i / 15)}-juego.png` });
}
await p.click('.salir-ampliada');
console.log('consola:', (await p.$eval('.consola-editor', (e) => e.innerText)).slice(-1500));
console.log('ERRORES:', errores.slice(0, 20));
await nav.close();
await servidor.close();
